; Configuration file for RepRapFirmware on Duet 3 Main Board 6HC
; executed by the firmware on start-up
;
; generated by RepRapFirmware Configuration Tool v3.6.15 on Sat Sep 12 2026 11:33:33 GMT+0200 (Central European Summer Time)

; General
G90 ; absolute coordinates
M83 ; relative extruder moves
M550 P"VALKYRIE V2" ; set hostname

; Network
M552 P0.0.0.0 S1 ; configure Ethernet adapter
M586 P0 S1 ; configure HTTP

; Smart Drivers
M569 P0.0 S1 D2 ; driver 0.0 goes forwards (X axis)
M569 P0.1 S1 D2 ; driver 0.1 goes forwards (Y axis)
M569 P0.2 S1 D2 ; driver 0.2 goes forwards (extruder 0)
M569 P0.3 S1 D2 ; driver 0.3 goes forwards (Z axis)
M569 P0.4 S1 D2 ; driver 0.4 goes forwards (Z axis)
M569 P0.5 S1 D2 ; driver 0.5 goes forwards (Z axis)

; Motor Idle Current Reduction
M906 I30 T30 ; set motor current idle factor and idle timeout

; Axes
M584 X0.0 Y0.1 Z0.3:0.4:0.5 ; set axis mapping
M350 X16 Y16 Z16 I1 ; configure microstepping with interpolation
M906 X2000 Y2000 Z800 ; set axis driver currents
M92 X100 Y100 Z400 ; configure steps per mm
M208 X0:330 Y0:300 Z0:275 ; set minimum and maximum axis limits
M566 X900 Y900 Z300 ; set maximum instantaneous speed changes (mm/min)
M203 X60000 Y60000 Z90000 ; set maximum speeds (mm/min)
M201 X10000 Y10000 Z500 ; set accelerations (mm/s^2)

; Extruders
M584 E0.2 ; set extruder mapping
M350 E16 I1 ; configure microstepping with interpolation
M906 E800 ; set extruder driver currents
M92 E932 ; configure steps per mm
M566 E600 ; set maximum instantaneous speed changes (mm/min)
M203 E6000 ; set maximum speeds (mm/min)
M201 E10000 ; set accelerations (mm/s^2)

; Kinematics
M669 K1 ; configure CoreXY kinematics

; Probes
M558 K0 P1 C"io3.in" H10 F300:120 T6000 A3 ; configure analog probe via slot #0
G31 P500 X0 Y-20 Z0 ; set Z probe trigger value, offset and trigger height

; Endstops
M574 X1 S3 ; configure X axis endstop
M574 Y1 S3 ; configure Y axis endstop
M574 Z2 S4 ; configure Z axis endstop

; Mesh Bed Compensation
M557 X25:305 Y25:275 S40:40 ; define grid for mesh bed compensation

; Sensors
M308 S0 P"temp3" Y"thermistor" A"Heated Bed" T100000 B4725 C7.06e-8 ; configure sensor #0
M308 S1 P"temp0" Y"pt1000" A"Nozzle" ; configure sensor #1
M308 S2 P"temp2" Y"thermistor" A"Chamber" T100000 B4725 C7.06e-8 ; configure sensor #2
M308 S3 P"temp1" Y"thermistor" A"Extruder" T100000 B4725 C7.06e-8 ; configure sensor #3

; Heaters
M950 H0 C"out9" T0 ; create heater #0
M143 H0 P0 T0 C0 S140 A0 ; configure heater monitor #0 for heater #0
M307 H0 R2.43 D5.5 E1.35 K0.56 B0 ; configure model of heater #0
M950 H1 C"out1" T1 ; create heater #1
M143 H1 P0 T1 C0 S285 A0 ; configure heater monitor #0 for heater #1
M307 H1 R2.43 D5.5 E1.35 K0.56 B0 ; configure model of heater #1
M950 H2 C"out8" T2 ; create heater #2
M143 H2 P0 T1 C0 S285 A0 ; configure heater monitor #0 for heater #2
M307 H2 R2.43 D5.5 E1.35 K0.56 B1 ; configure model of heater #2
M950 H3 C"out7" T2 ; create heater #3
M143 H3 P0 T1 C0 S285 A0 ; configure heater monitor #0 for heater #3
M307 H3 R2.43 D5.5 E1.35 K0.56 B1 ; configure model of heater #3

; Heated beds
M140 P0 H0 ; configure heated bed #0

; Fans
M950 F0 C"out3" ; create fan #0
M106 P0 C"CPAP Fan" S0 L0 X1 B0.1 ; configure fan #0
M950 F1 C"out6+out6.tach" ; create fan #1
M106 P1 C"Chamber Fan" S0 L0 X1 B0.1 ; configure fan #1
M950 F2 C"out5+out5.tach" ; create fan #2
M106 P2 C"Drybox Fan" S0 L0 X1 B0.1 ; configure fan #2
M950 F3 C"out2" ; create fan #3
M106 P3 C"PCB Fan" S0 L0 X1 B0.1 ; configure fan #3
M950 F4 C"out4+out4.tach" ; create fan #4
M106 P4 C"Water Pump" S0 X1 B0.1 H1 T45 ; configure fan #4

; Tools
M563 P0 D0 H1 F0 ; create tool #0
M568 P0 R0 S0 ; set initial tool #0 active and standby temperatures to 0C

; Miscellaneous
T0 ; select first tool
