; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Fri Mar 04 2022 20:32:00 GMT+0100 (sentraleuropeisk normaltid)
G91                    ; relative positioning
G1 H2 Z5 F6000         ; lift Z relative to current position
G1 H1 X235 Y-215 F1800 ; move quickly to X or Y endstop and stop there (first pass)
G1 H1 X235             ; home X axis
G1 H1 Y-215            ; home Y axis
G1 X-5 Y5 F6000        ; go back a few mm
G1 H1 X235 F360        ; move slowly to X axis endstop once more (second pass)
G1 H1 Y-215            ; then move slowly to Y axis endstop
G90                    ; absolute positioning
G1 X15 Y15 F6000       ; go to first bed probe point and home Z
G30                    ; home Z by probing the bed

; Uncomment the following lines to lift Z after probing
;G91                   ; relative positioning
;G1 Z5 F100            ; lift Z relative to current position
;G90                   ; absolute positioning


