; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Fri Mar 04 2022 20:32:00 GMT+0100 (sentraleuropeisk normaltid)
M280 P0 S90 ; retract BLTouch

