; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Fri Mar 04 2022 20:32:01 GMT+0100 (sentraleuropeisk normaltid)

