; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Fri Mar 04 2022 20:32:01 GMT+0100 (sentraleuropeisk normaltid)
; Wait for set temperatures to be reached
M116 P0

