; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Thu Dec 02 2021 19:16:54 GMT+0100 (sentraleuropeisk normaltid)
M83            ; relative extruder moves
G1 E-1 F3600  ; retract 10mm of filament
G91            ; relative positioning
G1 Z5 F360     ; lift Z by 5mm
G90            ; absolute positioning
G1 X0 F12000 ; go to X=0 Y=0

