; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Thu Dec 02 2021 19:16:54 GMT+0100 (sentraleuropeisk normaltid)

