; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Thu Dec 02 2021 19:16:54 GMT+0100 (sentraleuropeisk normaltid)
; Wait for set temperatures to be reached
M116 P0

