; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.6.15 on Sat Sep 12 2026 11:33:38 GMT+0200 (Central European Summer Time)

; home Z
G91 ; relative positioning
var maxTravel = move.axes[2].max - move.axes[2].min + 5 ; calculate how far Z can travel plus 5mm
G1 H1 Z{var.maxTravel} F600 ; coarse home in the +Z direction
G1 Z-5 F6000 ; move back 5mm
G1 H1 Z{var.maxTravel} F300 ; fine home in the +Z direction
G90 ; absolute positioning
