; pause.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.6.15 on Sat Sep 12 2026 11:33:38 GMT+0200 (Central European Summer Time)
M83 ; relative extruder moves
G1 E-10 F3600 ; retract 10mm of filament
G91 ; relative positioning
G1 Z5 F360 ; lift Z by 5mm
G90 ; absolute positioning
G1 X0 Y0 F6000 ; go to X=0 Y=0
