; resume.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.6.15 on Sat Sep 12 2026 11:33:38 GMT+0200 (Central European Summer Time)
G1 R1 X0 Y0 Z5 F6000 ; go to 5mm above position of the last move
G1 R1 X0 Y0 Z0 ; go back to the last print move
M83 ; relative extruder moves
G1 E10 F3600 ; extrude 10mm of filament
